# Configuration SonarCloud pour ecommerce-api (JavaScript/Node.js)

# Clé du projet - à récupérer dans l'URL SonarCloud
# Format : ton_org_github-ton_nom_de_projet
sonar.projectKey=Loocist23_ynov-ecommerce

# Organisation SonarCloud
sonar.organization=loocist23

# Nom et version du projet
sonar.projectName=ynov-ecommerce
sonar.projectVersion=1.0

# Encodage
sonar.sourceEncoding=UTF-8


# Dossier source principal
sonar.sources=src

# Langage principal
sonar.language=js

# Exclusions (fichiers à ne pas analyser)
sonar.exclusions=node_modules/**,test/**,**/*.test.js,**/*.spec.js,.husky/**,.github/**

# Fichiers de test (optionnel, pour couverture)
sonar.tests=test
sonar.test.inclusions=**/*.test.js

# Couverture de test (si tu utilises jest/lcov)
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Dossier de sortie du build (optionnel)
src=src
